# Generated by Django 4.1.4 on 2023-03-03 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_alter_listing_bath_rooms_alter_listing_sqrt'),
        ('realtors', '0005_alter_realtor_balance'),
        ('ServiceFee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefee',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='servicefee',
            name='realtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='realtors.realtor'),
        ),
    ]
