# Generated by Django 4.1.4 on 2023-02-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0002_alter_subscriber_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='city',
            field=models.CharField(default='shager', max_length=111),
        ),
    ]
