# Generated by Django 4.1.4 on 2023-01-19 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_alter_realtor_email'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realtors', to='realtors.realtor'),
        ),
    ]
