# Generated by Django 4.1.4 on 2023-01-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_sqrt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sqrt',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
    ]
