# Generated by Django 4.1.4 on 2023-02-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='avgRating',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='ratings',
        ),
    ]
