# Generated by Django 4.1.4 on 2023-02-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_listing_avgrating_remove_listing_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
