# Generated by Django 4.1.4 on 2023-02-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_listing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('Sale', 'For Sale'), ('Rent', 'For Rent')], default='Sale', max_length=10),
        ),
    ]
