# Generated by Django 4.1.4 on 2023-02-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listing_longitude_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Latitude_city',
            new_name='Latitude_of_city',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='Longitude_city',
            new_name='Longitude_of_city',
        ),
    ]
