# Generated by Django 4.1.4 on 2023-03-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_listing_latitude_of_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Latitude_of_city',
            field=models.DecimalField(decimal_places=2, default=9.005401, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='Longitude_of_city',
            field=models.DecimalField(decimal_places=2, default=38.763611, max_digits=10, null=True),
        ),
    ]
