# Generated by Django 4.1.4 on 2023-03-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_remove_listing_latitude_of_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=144, max_digits=10),
        ),
    ]
