# Generated by Django 4.1.4 on 2023-01-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_remove_favorite_realtor_favorite_realtor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='realtor_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
