# Generated by Django 4.1.4 on 2023-01-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_alter_favorite_realtor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='realtor_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
