# Generated by Django 4.1.4 on 2023-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_realtor',
            field=models.BooleanField(default=False),
        ),
    ]
