# Generated by Django 4.1.4 on 2023-02-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_is_realtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='is_realtor',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
