# Generated by Django 4.1.4 on 2023-02-04 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_alter_realtor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='date_hired',
            new_name='created_at',
        ),
    ]
