# Generated by Django 4.1.4 on 2023-03-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_rename_date_hired_realtor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
