# Generated by Django 4.1.4 on 2023-03-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_realtor_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='balance',
            field=models.FloatField(default=100.0),
        ),
    ]
