# Generated by Django 4.1.4 on 2023-02-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
