# Generated by Django 4.1.4 on 2023-03-01 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_rename_latitude_city_listing_latitude_of_city_and_more'),
        ('order', '0003_remove_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_listing', to='listings.listing'),
        ),
    ]
